galaxy_info:
  author: "Nacho de Lecea"
  description: "Tecnico de Sistemas"
  company: "PSS-TI"
  license: "MIT"

  min_ansible_version: "2.1"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - webserver
    - nginx

dependencies: []
