---
app_repo_url: "https://github.com/nachodele/PSS-Talent.git"
app_repo_version: "main"
app_base_dir: "/opt/pr-app"
app_image_name: "pr-app-image"
app_container_name: "pr-app"
app_container_port: "5000"
app_repo_subdir: "Trabajo-Final/Dev-Workspace"
