- name: Install Apache and PHP packages
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - php-mysql
    state: present
    update_cache: yes

- name: Download WordPress archive latest
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress-latest.tar.gz
    mode: '0644'

- name: Extract WordPress archive
  ansible.builtin.unarchive:
    src: /tmp/wordpress-latest.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Configure wp-config.php
  ansible.builtin.template:
    src: files/wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Ensure apache2 service is running and enabled
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
