name: CI - Infra y Config

on:
  pull_request:
    types: [edited, synchronize, reopened]

permissions:
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_DIR: ./Trabajo-Final/Dev-Workspace/terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform FMT Check
        run: terraform -chdir=${{ env.TERRAFORM_DIR }} fmt -recursive -check

      - name: Terraform Init (sin backend)
        run: terraform -chdir=${{ env.TERRAFORM_DIR }} init -backend=false

      - name: Terraform Validate
        run: terraform -chdir=${{ env.TERRAFORM_DIR }} validate

  ansible-ci:
    runs-on: ubuntu-latest
    needs: terraform-ci
    env:
      ANSIBLE_DIR: ./Trabajo-Final/Dev-Workspace/ansible

    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible 8.x + ansible-lint
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install "ansible-core==2.15.12" "ansible==8.7.0" ansible-lint

      - name: Lint Ansible playbooks
        working-directory: ${{ env.ANSIBLE_DIR }}
        run: ansible-lint .
